//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_tblDemoGraphicalTag
    {
        public int DemographicalId { get; set; }
        public Nullable<int> LevelId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> StateNewId { get; set; }
    }
}
