//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplyDiscount
    {
        public int ApplyDId { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public string Rate { get; set; }
        public Nullable<System.DateTime> EffextiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ValidityDateFrom { get; set; }
        public Nullable<System.DateTime> ValidityDateTo { get; set; }
        public string ApplyType { get; set; }
        public Nullable<int> Contractid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string RateType { get; set; }
        public Nullable<int> Zoneid { get; set; }
        public Nullable<int> Districtid { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<System.DateTime> ADCreatedDate { get; set; }
        public Nullable<System.DateTime> ADUpdatedDate { get; set; }
        public Nullable<int> ADCreatedBy { get; set; }
        public Nullable<int> ADUpdatedBy { get; set; }
    }
}
