//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplySurchargeHeader
    {
        public int SurchargeHeaderId { get; set; }
        public Nullable<int> SurchargeId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string MOQ { get; set; }
        public string RateType { get; set; }
        public Nullable<double> Value { get; set; }
        public string ApplyType { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> cityid { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> Zoneid { get; set; }
        public Nullable<int> Districtid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<int> countryid { get; set; }
        public Nullable<System.DateTime> SCreatedDate { get; set; }
        public Nullable<System.DateTime> SUpdatedDate { get; set; }
        public Nullable<int> SCreatedBy { get; set; }
        public Nullable<int> SUpdatedBy { get; set; }
    }
}
