//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActivityComment
    {
        public int CommentId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
