//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBranch
    {
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string BranchHead { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Abbreviation { get; set; }
        public string Zone { get; set; }
        public string District { get; set; }
        public string NewBranchId { get; set; }
        public int LanguageId { get; set; }
        public string Initial { get; set; }
        public Nullable<int> ApprovalLevel1 { get; set; }
        public Nullable<int> ApprovalLevel2 { get; set; }
        public Nullable<int> ApprovalLevel3 { get; set; }
        public string WSURL { get; set; }
        public string HotLineNo { get; set; }
        public string InvoiceAmountR { get; set; }
        public string Uploadlogo { get; set; }
        public string SmsNotificationFlag { get; set; }
        public string EmailNotificationFlag { get; set; }
        public Nullable<int> BusinessUnit { get; set; }
        public Nullable<int> regionid { get; set; }
        public Nullable<int> stateid { get; set; }
        public string PostalCodeA { get; set; }
    }
}
