//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessUnitHoliday
    {
        public int BusinessUnitHolidayID { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> HolidayId { get; set; }
    }
}
