//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessUnitBranch
    {
        public int BUBId { get; set; }
        public string Branchid { get; set; }
        public string BranchName { get; set; }
        public string Abbreviation { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Countryid { get; set; }
        public string Regionid { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string District { get; set; }
        public string Pincode { get; set; }
        public string BusinessUnitId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Zone { get; set; }
    }
}
