//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int CompanyId { get; set; }
        public Nullable<int> ContactTypeId { get; set; }
        public string CompanyName { get; set; }
        public string NickName { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Tel { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Fax { get; set; }
        public string Fax2 { get; set; }
        public string Fax3 { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> CustomerGroupId { get; set; }
        public Nullable<int> CustomerCategoryId { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<int> KeyAccountManager { get; set; }
        public Nullable<int> AccessRightsId { get; set; }
        public Nullable<int> EnquirySourceId { get; set; }
        public string EnquirySourceName { get; set; }
        public Nullable<int> CustomerStatusId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Portfolio { get; set; }
        public Nullable<float> BankId { get; set; }
        public Nullable<float> BankBranchId { get; set; }
        public string BankAcctId { get; set; }
        public string NricNo { get; set; }
        public string Employeeof { get; set; }
        public string Remark { get; set; }
        public string Gender { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string Mobile4 { get; set; }
        public string Office1 { get; set; }
        public string Office2 { get; set; }
        public string Office3 { get; set; }
        public string CustNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerId { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public string Phone2 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public Nullable<System.DateTime> LUDate { get; set; }
        public Nullable<int> LUBy { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> ActiveSince { get; set; }
        public string ASReason { get; set; }
        public Nullable<System.DateTime> UnFreezeSince { get; set; }
        public string UFReason { get; set; }
        public Nullable<bool> ICompanySales { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Freeze { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> DepositAmount { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<bool> SendSms { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> CCenter_on_orderPage { get; set; }
    }
}
