//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractMService
    {
        public int ContractMServiceId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> MServiceId { get; set; }
        public Nullable<double> MinimumCharge { get; set; }
        public Nullable<double> MCharageAmount { get; set; }
    }
}
