//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyBranch
    {
        public int CBranchId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string BranchName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string BranchHead { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string Address4 { get; set; }
        public string NickName { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string NewBranchId { get; set; }
        public string Phone1 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<bool> Billable { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> LUDate { get; set; }
        public Nullable<int> LUBy { get; set; }
        public Nullable<System.DateTime> ActiveSince { get; set; }
        public string ASReason { get; set; }
        public Nullable<System.DateTime> UnFreezeSince { get; set; }
        public string UFReason { get; set; }
        public Nullable<int> HigherLevel { get; set; }
        public string CCNo { get; set; }
        public string LevelNo { get; set; }
        public Nullable<bool> DActive { get; set; }
        public Nullable<bool> DFreeze { get; set; }
        public string LoginQPin { get; set; }
        public string DLUByType { get; set; }
        public Nullable<int> ApprovalLevel1 { get; set; }
        public Nullable<int> ApprovalLevel2 { get; set; }
        public Nullable<int> ApprovalLevel3 { get; set; }
        public string DCreatedByType { get; set; }
        public string ContactName { get; set; }
        public string Department { get; set; }
        public Nullable<int> Regionid { get; set; }
        public Nullable<int> Stateid { get; set; }
        public string Delivery { get; set; }
        public string Collection { get; set; }
        public string BLatitude { get; set; }
        public string BLongitude { get; set; }
    }
}
