//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyAddress
    {
        public int AddressId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string LandMark { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> LUDate { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> LUBy { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public Nullable<int> StateNewid { get; set; }
        public Nullable<int> Regionid { get; set; }
        public string Email { get; set; }
    }
}
