//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyAddressBook
    {
        public int CABid { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CostCenterName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> Countryid { get; set; }
        public Nullable<int> Regionid { get; set; }
        public Nullable<int> Stateid { get; set; }
        public Nullable<int> Cityid { get; set; }
        public Nullable<int> Zoneid { get; set; }
        public Nullable<int> Districtid { get; set; }
        public string PostalCode { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber1 { get; set; }
        public string ContactNumber2 { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public string Ext1 { get; set; }
        public string Ext2 { get; set; }
        public string Department { get; set; }
        public string Collection_Instruction { get; set; }
        public Nullable<int> CBranchId { get; set; }
        public string BranchName { get; set; }
        public string ALatitude { get; set; }
        public string ALongitude { get; set; }
    }
}
