//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactCostCentre
    {
        public int ContactCostCentreID { get; set; }
        public int CBranchId { get; set; }
        public int ContactId { get; set; }
        public string CreatedByType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
