//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcontactaddress
    {
        public int ContactAddressid { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Collect { get; set; }
        public string Deliver { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> stateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
