//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractService
    {
        public int CServiceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> BusinessLineId { get; set; }
        public Nullable<int> SubBusinessLineId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> MinChargeAmt { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<double> FlatMFees { get; set; }
        public string Tax { get; set; }
        public Nullable<System.DateTime> CSCreatedDate { get; set; }
        public Nullable<System.DateTime> CSUpdatedDate { get; set; }
        public Nullable<int> CSCreatedBy { get; set; }
        public Nullable<int> CSUpdatedBy { get; set; }
        public string FSMS { get; set; }
        public string FEMAIL { get; set; }
    }
}
