//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyPartner
    {
        public int PartnerId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string PartnerName { get; set; }
        public string PDescription { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
