//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactParameter
    {
        public int ContactParameterId { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string BelongsTo { get; set; }
    }
}
