//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyProfile
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string CountryId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebsiteURL { get; set; }
        public string LogoFile { get; set; }
        public Nullable<int> LicenseQty { get; set; }
        public Nullable<System.DateTime> LicenseStartDate { get; set; }
        public Nullable<System.DateTime> LicenseEndDate { get; set; }
        public Nullable<bool> SMSService { get; set; }
        public Nullable<bool> CustomerArea { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string UOM { get; set; }
        public string TopBgColor { get; set; }
        public Nullable<bool> UDR { get; set; }
        public Nullable<bool> ENotification { get; set; }
        public Nullable<double> GST { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
