//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractCostCentre
    {
        public int ContractCostCentreID { get; set; }
        public int CBranchId { get; set; }
        public int ContractId { get; set; }
        public string CreatedByType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> BillingCBranchId { get; set; }
        public Nullable<System.DateTime> CCCreatedDate { get; set; }
        public Nullable<System.DateTime> CCUpdatedDate { get; set; }
        public Nullable<int> CCCreatedBy { get; set; }
        public Nullable<int> CCUpdatedBy { get; set; }
    }
}
