//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContact
    {
        public int ContactId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string PinCode { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DesignationId { get; set; }
        public string Department { get; set; }
        public string YOG { get; set; }
        public string Tel { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> KeyAccountManger { get; set; }
        public Nullable<int> ContactAccountManager { get; set; }
        public Nullable<bool> SyncWithOutlook { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<int> EnquirySourceId { get; set; }
        public string EnquirySourceName { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Block { get; set; }
        public string Division { get; set; }
        public Nullable<bool> DContact { get; set; }
        public string Section { get; set; }
        public string Gender { get; set; }
        public string CPassword { get; set; }
        public string Extension2 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string Extension1 { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LUDate { get; set; }
        public Nullable<int> LUBy { get; set; }
        public Nullable<int> CBranchId { get; set; }
        public string CostCenterId { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> ActiveFrom { get; set; }
        public Nullable<System.DateTime> ActiveTo { get; set; }
        public Nullable<System.DateTime> test { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedByType { get; set; }
        public string LUByType { get; set; }
        public string ContactType { get; set; }
        public Nullable<System.DateTime> PasswordRenewdate { get; set; }
        public Nullable<bool> RenewStatus { get; set; }
        public Nullable<int> IntervalInDay { get; set; }
        public Nullable<bool> tempPassFlg { get; set; }
        public Nullable<int> Regionid { get; set; }
        public Nullable<int> Zoneid { get; set; }
        public string Collection { get; set; }
        public string Delivery { get; set; }
        public string CLoginQPin { get; set; }
        public string FAddress { get; set; }
    }
}
