//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyImported
    {
        public Nullable<double> No { get; set; }
        public Nullable<int> Indutry { get; set; }
        public string Mr_Ms { get; set; }
        public string Name { get; set; }
        public string Email_Address { get; set; }
        public string Designation { get; set; }
        public string caTEGOORYiD { get; set; }
        public string ContactiD { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
