//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerBranchTiming
    {
        public int CBTimingId { get; set; }
        public Nullable<int> CBranchId { get; set; }
        public string Day { get; set; }
        public Nullable<System.DateTime> TimeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public Nullable<System.DateTime> LunchFrom { get; set; }
        public Nullable<System.DateTime> LunchTo { get; set; }
        public Nullable<bool> HalfDay { get; set; }
        public Nullable<System.DateTime> TCreatedDate { get; set; }
        public Nullable<System.DateTime> TUpdatedDate { get; set; }
        public Nullable<int> TCreatedBy { get; set; }
        public Nullable<int> TUpdatedBy { get; set; }
    }
}
