//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCallBooking
    {
        public int CallId { get; set; }
        public Nullable<float> CustomerId { get; set; }
        public Nullable<float> ProductId { get; set; }
        public Nullable<float> InstallationNumber { get; set; }
        public Nullable<float> SerialNumber { get; set; }
        public string CallDescription { get; set; }
        public Nullable<float> CallTypeId { get; set; }
        public string CallMode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public string MaintType { get; set; }
        public string EngineerRemark { get; set; }
        public string CustomerFeedback { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Allocated { get; set; }
    }
}
