//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyOEM
    {
        public int OEMId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string OEMCompanyName { get; set; }
        public string Description { get; set; }
    }
}
