//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyAddress2
    {
        public int AddressId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CountryId { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
