//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscountmaster
    {
        public int DiscountId { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountName { get; set; }
        public Nullable<int> BId { get; set; }
        public Nullable<System.DateTime> DCreatedDate { get; set; }
        public Nullable<System.DateTime> DUpdatedDate { get; set; }
        public Nullable<int> DCreatedBy { get; set; }
        public Nullable<int> DUpdatedBy { get; set; }
    }
}
