//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDictionary
    {
        public string LabelId { get; set; }
        public string PageId { get; set; }
        public string English { get; set; }
        public string Simplified_Chinese { get; set; }
        public string Traditional_Chinese { get; set; }
        public string Bahasa_Indonesia { get; set; }
        public string Sinhala { get; set; }
        public int Identification { get; set; }
        public int Id { get; set; }
        public Nullable<int> NodeId { get; set; }
    }
}
