//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnquiry
    {
        public int EnquiryId { get; set; }
        public int CustomerId { get; set; }
        public string ProjectName { get; set; }
        public string EnquiryDesc { get; set; }
        public Nullable<bool> EnqProspect { get; set; }
        public Nullable<System.DateTime> EFoundDate { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<double> EClosingValue { get; set; }
        public Nullable<int> ClosingCurrencyId { get; set; }
        public Nullable<int> EProbability { get; set; }
        public Nullable<int> EnquirySourceId { get; set; }
        public Nullable<int> EIncharge { get; set; }
        public Nullable<int> CustomerContact { get; set; }
        public string ManagerComm { get; set; }
        public string SalesPersonComm { get; set; }
        public string CEOComm { get; set; }
        public string EnqReferenceNumber { get; set; }
        public Nullable<int> SalesCycleId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> KeyingPerson { get; set; }
        public string EnquirySourceName { get; set; }
        public Nullable<short> Type { get; set; }
        public string ProjectRelatedInfo { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
