//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHubmaster
    {
        public int Hubid { get; set; }
        public string I_HubTransit { get; set; }
        public string Hub_discription { get; set; }
        public string BranchCode { get; set; }
        public string type { get; set; }
        public string hubcode { get; set; }
    }
}
