//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHelp
    {
        public int HelpId { get; set; }
        public Nullable<int> NodeGroupId { get; set; }
        public Nullable<int> NodeId { get; set; }
        public string PageDescription { get; set; }
        public string HelpDescription { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
