//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceHeader
    {
        public int InvoiceId { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> CreditTermCode { get; set; }
        public Nullable<float> InvoiceAmount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<float> BalanceAmount { get; set; }
        public Nullable<float> AmountReceived { get; set; }
        public string CompanyId { get; set; }
        public string Note { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> SODate { get; set; }
        public string DRemark { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<int> SalesPersonId { get; set; }
        public Nullable<int> OStatus { get; set; }
        public Nullable<bool> Submit { get; set; }
        public string ReceiptNo { get; set; }
        public string SosofNo { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PickupTime { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Volume1 { get; set; }
        public Nullable<double> Volume2 { get; set; }
        public Nullable<double> Volume3 { get; set; }
        public Nullable<double> EstimatedCost { get; set; }
        public Nullable<int> BillTo { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string CreatedByType { get; set; }
        public string UpdatedByType { get; set; }
        public Nullable<int> ReturnOrderId { get; set; }
        public string BillToType { get; set; }
        public string approve { get; set; }
        public string OrderType { get; set; }
        public string OrderTypeNo { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedByType { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<bool> ReturnService { get; set; }
        public Nullable<int> CBranchId { get; set; }
        public string AlternateRefNo { get; set; }
        public string RequestorName { get; set; }
        public Nullable<int> QuantityUomId { get; set; }
        public string ContractCostCntrDprt { get; set; }
        public string receiptFile { get; set; }
        public string parentChild { get; set; }
        public string BillToVal { get; set; }
        public string WalkInFlag { get; set; }
        public Nullable<bool> PaidFlag { get; set; }
        public string CreatedFrom { get; set; }
        public string ContentFile { get; set; }
        public string ReferenceNumber { get; set; }
        public string RequestorContact { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string ItemType { get; set; }
        public Nullable<bool> SwapAddress { get; set; }
        public string Record_Type { get; set; }
        public string LI { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Cust_Reference { get; set; }
        public string Aano { get; set; }
        public string Segment { get; set; }
        public string Segment1 { get; set; }
        public string OEmail { get; set; }
        public string OMobile { get; set; }
        public string OWeightUOM { get; set; }
        public string OVolumeUOM { get; set; }
        public Nullable<int> WinPeriodId { get; set; }
    }
}
