//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceHeadertemp
    {
        public int InvoicetempId { get; set; }
        public string Order_Number { get; set; }
        public string Reference_number { get; set; }
        public string Service_Type { get; set; }
        public System.DateTime Collection_DateTime { get; set; }
        public System.DateTime Delivery_DateTime { get; set; }
        public string Item_Type { get; set; }
        public int Item_Qty { get; set; }
        public string Collection_Company { get; set; }
        public string Collection_Address1 { get; set; }
        public string Collection_Address2 { get; set; }
        public string Collection_Address3 { get; set; }
        public string Collection_PostalCode { get; set; }
        public string Collection_Country { get; set; }
        public string Collection_City { get; set; }
        public string Collection_District { get; set; }
        public string Collection_ContactPerson { get; set; }
        public string Collection_Phone1 { get; set; }
        public string Collection_Phone2 { get; set; }
        public string Collection_Instruction { get; set; }
        public string Delivery_Company { get; set; }
        public string Delivery_Address1 { get; set; }
        public string Delivery_Address2 { get; set; }
        public string Delivery_Address3 { get; set; }
        public string Delivery_PostalCode { get; set; }
        public string Delivery_Country { get; set; }
        public string Delivery_City { get; set; }
        public string Delivery_District { get; set; }
        public string Delivery_ContactPerson { get; set; }
        public string Delivery_Phone1 { get; set; }
        public string Delivery_Phone2 { get; set; }
        public string Delivery_Instruction { get; set; }
        public string Special_Instruction { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string Requestor_Name { get; set; }
        public string Collection_Address4 { get; set; }
        public string Delivery_Address4 { get; set; }
    }
}
