//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceAddressOrder
    {
        public int InvoiceAddressId { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string SpecialInstruction { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Address4 { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string BranchName { get; set; }
        public string ContactName { get; set; }
        public string PostalCode { get; set; }
        public string Department { get; set; }
        public string Phone1 { get; set; }
        public string Extension1 { get; set; }
        public string Extension2 { get; set; }
        public Nullable<int> CBranchId { get; set; }
        public Nullable<int> Regionid { get; set; }
        public Nullable<int> Statenewid { get; set; }
    }
}
