//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceSalesPerson
    {
        public int ISalesPersonId { get; set; }
        public string Department { get; set; }
        public Nullable<float> SalesPersonId { get; set; }
        public string InvoiceId { get; set; }
    }
}
