//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceHeaderTempDoc
    {
        public int InvoicetempID { get; set; }
        public string Record_Type { get; set; }
        public string LI { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Cust_Reference { get; set; }
        public string Aano { get; set; }
        public string Segment { get; set; }
        public string Tel_No { get; set; }
        public string Sol_Name { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string State { get; set; }
    }
}
