//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryPrice
    {
        public int InventoryPriceId { get; set; }
        public string InventoryId { get; set; }
        public Nullable<double> Price { get; set; }
        public string PStatus { get; set; }
        public string Code { get; set; }
    }
}
