//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIPublisherRequirement
    {
        public int InvoicePRId { get; set; }
        public string InvoiceId { get; set; }
        public string PEffortKey { get; set; }
        public string Option1 { get; set; }
        public string ClientNo { get; set; }
    }
}
