//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstallation
    {
        public int InstallationNUmber { get; set; }
        public Nullable<float> CustomerId { get; set; }
        public Nullable<float> ProductId { get; set; }
        public string CardNo { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<float> SellingCurencyId { get; set; }
        public Nullable<double> SellingAmount { get; set; }
    }
}
