//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public string InvoiceId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ServiceType { get; set; }
    }
}
