//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLevel
    {
        public double LevelId { get; set; }
        public string LevelName { get; set; }
        public string LevelDesc { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
