//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMRateMatrix
    {
        public int MRateMatrixId { get; set; }
        public Nullable<int> MServiceId { get; set; }
        public string MLevelName { get; set; }
        public string Type { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Discount { get; set; }
    }
}
