//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMassEmail
    {
        public int Id { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string From { get; set; }
    }
}
