//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNode
    {
        public int NodeId { get; set; }
        public int NodeGroupId { get; set; }
        public string NodeName { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Url { get; set; }
        public int LanguageId { get; set; }
    }
}
