//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodesAccess
    {
        public int UserAccessId { get; set; }
        public int UserId { get; set; }
        public int NodeGroupId { get; set; }
        public int NodeId { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<bool> FullAccess { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
