//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderSM
    {
        public int SMSId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Mobile { get; set; }
        public string SAddressType { get; set; }
    }
}
