//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDiscount
    {
        public int OrderDiscountId { get; set; }
        public string OrderId { get; set; }
        public string DiscountId { get; set; }
        public string DiscountValue { get; set; }
        public string userid { get; set; }
        public string LoginId { get; set; }
        public string Password { get; set; }
        public string Serviceid { get; set; }
    }
}
