//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderpackageContent
    {
        public int OrderpackageContentid { get; set; }
        public string orderid { get; set; }
        public string ServiceId { get; set; }
        public string PackageContent { get; set; }
    }
}
