//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderMaster
    {
        public int OrderId { get; set; }
        public string OrderName { get; set; }
        public string Stage { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> Completion { get; set; }
    }
}
