//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblorderSurcharge
    {
        public int orderSurchargeId { get; set; }
        public Nullable<int> ApplySurchrgeId { get; set; }
        public Nullable<double> SurchargeValue { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SurchargeId { get; set; }
        public string RateType { get; set; }
    }
}
