//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderTracking
    {
        public int OrderStatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> OrderDeliveryDate { get; set; }
        public Nullable<System.DateTime> OrderLastUpdateDate { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string Status { get; set; }
        public string OrderNo { get; set; }
    }
}
