//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductLedger
    {
        public int TransId { get; set; }
        public Nullable<float> ProductId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> InOut { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<float> EntityType { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> ClosingStock { get; set; }
        public Nullable<int> OpeningStock { get; set; }
    }
}
