//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTree
    {
        public int Id { get; set; }
        public double LevelId { get; set; }
        public int ParentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string IconFileName { get; set; }
        public string PictureFileName { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Price { get; set; }
        public string BrochureFile { get; set; }
        public string Feature { get; set; }
        public string TechincalSpecification { get; set; }
        public Nullable<bool> PostToWeb { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> SCountDate { get; set; }
        public Nullable<double> CurrentStock { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> MinQty { get; set; }
        public Nullable<double> ReOrderQty { get; set; }
        public Nullable<float> UOM1 { get; set; }
        public Nullable<double> UnitCost { get; set; }
        public string SupplierId { get; set; }
        public Nullable<double> Probability { get; set; }
        public string ProductType { get; set; }
        public string ProductCode { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int LanguageId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> WebSflag { get; set; }
    }
}
