//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMonthlyTargetList
    {
        public int MTargetListId { get; set; }
        public Nullable<float> PMonthlyTargetId { get; set; }
        public Nullable<float> TargetCustomerId { get; set; }
        public Nullable<double> ExpectedAmount { get; set; }
        public Nullable<int> CallStatusId { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public string Description { get; set; }
        public Nullable<float> ContactPersonId { get; set; }
    }
}
