//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPicture
    {
        public int PictureId { get; set; }
        public Nullable<float> ProductId { get; set; }
        public string IconicPictue { get; set; }
        public string BigPicture { get; set; }
        public Nullable<bool> MainPicture { get; set; }
    }
}
