//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<float> ParentId { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> ProductType { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public Nullable<float> Currency { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> EOQ { get; set; }
        public Nullable<float> TaxId { get; set; }
        public Nullable<bool> Tax { get; set; }
        public Nullable<double> Term { get; set; }
        public Nullable<double> Period { get; set; }
        public Nullable<double> ClosePercentage { get; set; }
        public string Image { get; set; }
        public string OldImage { get; set; }
    }
}
