//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductTree1
    {
        public int Id { get; set; }
        public double LevelId { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public string IconFileName { get; set; }
        public string PictureFileName { get; set; }
        public string UOM { get; set; }
        public Nullable<double> Price { get; set; }
        public string BrochureFile { get; set; }
        public string Feature { get; set; }
        public string TechincalSpecification { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
