//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproductpriceFlag
    {
        public int PPFlagid { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> BusinessUnitid { get; set; }
        public string clientOScreen { get; set; }
        public string weekday { get; set; }
        public string publicHoliday { get; set; }
        public string returnService { get; set; }
        public string weekend { get; set; }
        public string cashpayment { get; set; }
        public string Eprocurment { get; set; }
        public string after_office_hours { get; set; }
        public string input_package_content { get; set; }
    }
}
