//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentDetail
    {
        public int PaymentId { get; set; }
        public string InvoiceId { get; set; }
        public Nullable<float> PaymentReceived { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> DueAmount { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<System.DateTime> DDDate { get; set; }
        public string PayDetail { get; set; }
        public Nullable<int> ChequeStatus { get; set; }
    }
}
