//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPasswordChangeAuditLog
    {
        public int PAuditLogId { get; set; }
        public string OldPassword { get; set; }
        public string NewPasword { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string ObjectType { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> ChangeBy { get; set; }
        public string ChangeByType { get; set; }
    }
}
