//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationHeader
    {
        public int QuotationId { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> CreditTermCode { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string SpecialNote { get; set; }
        public string Appendix { get; set; }
        public Nullable<bool> ShowTotal { get; set; }
        public Nullable<float> QuotationAmount { get; set; }
        public Nullable<float> CompanyId { get; set; }
    }
}
