//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationDetail
    {
        public int QuotationId { get; set; }
        public int ProductId { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<int> TexCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> SeqNo { get; set; }
    }
}
