//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReport
    {
        public int ReportId { get; set; }
        public string ReportNo { get; set; }
        public string English { get; set; }
        public string Simplified_Chinese { get; set; }
        public string Traditional_Chinese { get; set; }
        public string Bahasa_Indonesia { get; set; }
        public string Sinhala { get; set; }
        public string ReportType { get; set; }
        public string ReportUrl { get; set; }
        public Nullable<System.DateTime> ReportExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string AccessBy { get; set; }
    }
}
