//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRenewalList
    {
        public int RenewalId { get; set; }
        public Nullable<float> InventoryId { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public Nullable<double> Records { get; set; }
        public Nullable<double> SellingRate { get; set; }
        public Nullable<double> Probability { get; set; }
    }
}
