//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public int SupplierId { get; set; }
        public Nullable<int> ContactTypeId { get; set; }
        public string CompanyName { get; set; }
        public string NickName { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> SupplierGroupId { get; set; }
        public Nullable<int> SupplierCategoryId { get; set; }
        public Nullable<int> SupplierTypeId { get; set; }
        public Nullable<int> KeyAccountManager { get; set; }
        public Nullable<int> AccessRightsId { get; set; }
        public Nullable<int> EnquirySourceId { get; set; }
        public string EnquirySourceName { get; set; }
        public Nullable<int> SupplierStatusId { get; set; }
        public Nullable<int> SalesTerm { get; set; }
        public Nullable<double> CreditPeriod { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<double> DiscRate { get; set; }
        public Nullable<double> DiscPeriod { get; set; }
        public string Remark { get; set; }
        public Nullable<float> TaxId { get; set; }
        public string DRemark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Portfolio { get; set; }
        public string SupplierCode { get; set; }
    }
}
