//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockLedger
    {
        public int LedgerId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public string TransactionType { get; set; }
        public string TransactionNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ClosingBalance { get; set; }
    }
}
