//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierContact
    {
        public int SupplierContactId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PinCode { get; set; }
        public string NickName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string DesignationId { get; set; }
        public string Department { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public Nullable<int> KeyAccountManger { get; set; }
        public Nullable<bool> SyncWithOutlook { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<int> EnquirySourceId { get; set; }
        public string EnquirySourceName { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Block { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
