//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesPersonBalance
    {
        public int BalanceId { get; set; }
        public Nullable<float> SalesPersonId { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public Nullable<double> BalAmt { get; set; }
        public Nullable<double> Ratio { get; set; }
    }
}
