//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesPersonBalanceDetail
    {
        public int SPDetailId { get; set; }
        public Nullable<float> BalanceId { get; set; }
        public string InventoryId { get; set; }
        public Nullable<double> NoOfRecords { get; set; }
        public Nullable<double> SRate { get; set; }
        public Nullable<double> Prob { get; set; }
    }
}
