//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTree
    {
        public int TreeId { get; set; }
        public double Seq { get; set; }
        public Nullable<double> LevelId { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> IntFlag { get; set; }
        public string SessId { get; set; }
        public string PluseHtml { get; set; }
        public string Id2 { get; set; }
        public string Attach { get; set; }
        public Nullable<bool> IsRoot { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
