//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskHistory
    {
        public int TaskHistoryId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string TaskHistroryDate { get; set; }
        public string TaskHistroryTime { get; set; }
        public Nullable<int> MangerId { get; set; }
        public string ManagerComment { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserComment { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Close_Open { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
