//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int TaskId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public string TaskGroupId { get; set; }
        public string TaskName { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> ToBeDefineBy { get; set; }
        public Nullable<int> ToBeDoneBy { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string TaskStart { get; set; }
        public string Duration { get; set; }
        public Nullable<int> DurationUnit { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public Nullable<System.DateTime> DeadLineTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> DependencyTaskId { get; set; }
        public Nullable<System.DateTime> AccessTime { get; set; }
        public Nullable<int> ExternalEntityId { get; set; }
        public string FileDescription { get; set; }
        public string FileUploaded { get; set; }
        public string FontColor { get; set; }
        public Nullable<bool> NewTask { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DefindByPriority { get; set; }
        public Nullable<int> DoneByPriority { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTime> CloseAt { get; set; }
        public Nullable<int> VirtuallyDefinedById { get; set; }
        public Nullable<bool> SplitRights { get; set; }
        public Nullable<int> TaskSeq { get; set; }
        public string StatusAlert { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<System.DateTime> DoneAt { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
