//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaskGroup
    {
        public int TGroupId { get; set; }
        public string TaskGroupId { get; set; }
        public Nullable<int> TaskParentId { get; set; }
        public string TaskGroupName { get; set; }
    }
}
