//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTasksAssignedTo
    {
        public int TaskId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> DeadLineDate { get; set; }
        public string DeadLineTime { get; set; }
        public Nullable<System.DateTime> AccessTime { get; set; }
        public string FontColor { get; set; }
        public Nullable<int> DoneByPriority { get; set; }
        public Nullable<bool> Close { get; set; }
        public Nullable<System.DateTime> CloseAt { get; set; }
        public Nullable<int> VirtuallyDefinedById { get; set; }
        public Nullable<bool> SplitRights { get; set; }
        public Nullable<int> TaskSeq { get; set; }
        public string StatusAlert { get; set; }
        public Nullable<bool> Done { get; set; }
        public Nullable<System.DateTime> DoneAt { get; set; }
    }
}
