//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokenAuthenticationInWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserStrength
    {
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StrengthId { get; set; }
        public Nullable<bool> SW { get; set; }
        public Nullable<int> Sequency { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
